"""HTML Report Generator — renders SignalPackage into a standalone HTML snapshot.

Only non-blocked SignalPackages can be rendered. Reports are saved to
data/governance/reports/YYYY-MM-DD/{signal_id}.html.

This is a snapshot/archive output, NOT the main UI (Dashboard is the main UI).
"""

from __future__ import annotations

from datetime import date
from html import escape
from pathlib import Path
from urllib.parse import urlparse

from src.governance.models import SignalPackage
from src.governance.repository import GovernanceRepository


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Signal Report: {ticker} — {signal_id}</title>
<style>
body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; background: #0f1117; color: #e4e4e7; }}
h1 {{ font-size: 24px; border-bottom: 1px solid #333; padding-bottom: 8px; }}
h2 {{ font-size: 18px; margin-top: 24px; }}
.badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }}
.badge-pass {{ background: #166534; color: #86efac; }}
.badge-warn {{ background: #854d0e; color: #fde68a; }}
.badge-block {{ background: #991b1b; color: #fca5a5; }}
.section {{ margin: 16px 0; padding: 12px; background: #1a1d27; border-radius: 8px; }}
.label {{ font-size: 12px; color: #6b7280; text-transform: uppercase; }}
.value {{ font-size: 14px; }}
.evidence {{ margin: 8px 0; padding: 8px; background: #111; border-left: 3px solid #3b82f6; font-size: 13px; }}
.footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #333; font-size: 12px; color: #6b7280; }}
</style>
</head>
<body>
<h1>{ticker} — Signal Report</h1>
<div class="badge badge-{status_css}">{publish_status}</div>

<div class="section">
  <div class="label">Signal ID</div>
  <div class="value">{signal_id}</div>
</div>

<div class="section">
  <div class="label">Summary</div>
  <div class="value">{summary}</div>
</div>

<div class="section">
  <div class="label">Evidence ({evidence_count} items)</div>
  {evidence_html}
</div>

<div class="section">
  <div class="label">Publish Status</div>
  <div class="value">{publish_status}</div>
</div>

<div class="footer">
  Generated by Twitter Investor Distiller &mdash; Signal Governance Pipeline &mdash; {generated_at}<br>
  <strong>Disclaimer:</strong> This report is for research purposes only and does not constitute investment advice.
</div>
</body>
</html>"""


def _status_css(status: str) -> str:
    return {"pass": "pass", "warn": "warn"}.get(status, "block")


def _safe_url(url: str | None) -> str:
    if not url:
        return ""
    parsed = urlparse(url)
    if parsed.scheme not in {"http", "https"}:
        return ""
    return escape(url, quote=True)


def generate_html_report(package: SignalPackage) -> str | None:
    """Generate an HTML report from a SignalPackage.

    Returns None if the package is blocked or has no candidate.
    """
    if package.is_blocked():
        return None

    if package.candidate is None:
        return None

    evidence_html = ""
    for e in package.evidence:
        source_label = escape(e.source_type or "unknown", quote=True)
        excerpt = escape(e.excerpt or "(no excerpt)", quote=True)
        url = _safe_url(e.url)
        evidence_html += (
            f'<div class="evidence">'
            f'<span class="label">[{source_label}]</span> '
            f'<span>{excerpt}</span>'
            + (
                f' <a href="{url}" target="_blank" rel="noopener noreferrer" '
                f'style="color:#60a5fa;font-size:11px;">source</a>'
                if url
                else ""
            )
            + "</div>\n"
        )

    if not evidence_html:
        evidence_html = '<div class="value">No evidence recorded</div>'

    status_css = _status_css(package.publish_status)

    return _HTML_TEMPLATE.format(
        ticker=escape(package.ticker, quote=True),
        signal_id=escape(package.signal_id, quote=True),
        summary=escape(package.summary or "No summary", quote=True),
        publish_status=escape(package.publish_status, quote=True),
        status_css=status_css,
        evidence_count=len(package.evidence),
        evidence_html=evidence_html,
        generated_at=str(package.generated_at),
    )


def render_and_save_report(
    package: SignalPackage,
    repo: GovernanceRepository,
) -> Path | None:
    """Generate and persist an HTML report.

    Returns the file path, or None if generation was refused.
    """
    html = generate_html_report(package)
    if html is None:
        return None

    path = repo.base_dir / "reports" / date.today().isoformat() / f"{package.signal_id}.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path
